apiVersion: v1
kind: Service
metadata:
  name: freqtrade-lb
  namespace: freqtrade
spec:
  type: LoadBalancer
  selector:
    app: freqtrade
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080