{
 "title": "Nodes Temperature",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "pve (192.168.0.2)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"192.168.0.2:9100\"} > 0",
     "legendFormat": "{{chip}} - {{sensor}}"
    }
   ]
  },
  {
   "title": "pve-02 (192.168.0.200)",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"192.168.0.200:9100\"} > 0",
     "legendFormat": "{{chip}} - {{sensor}}"
    }
   ]
  },
  {
   "title": "external-services (192.168.0.201)",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"192.168.0.201:9100\"} > 0",
     "legendFormat": "{{chip}} - {{sensor}}"
    }
   ]
  }
 ]
}