{
 "title": "High level Sloth SLOs",
 "description": "A high level view of all Sloth SLOs",
 "tags": [
  "service levels",
  "sli",
  "slo",
  "sloth"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "min_burning_rate", "label": "Min Burning rate", "query": "1" }
  ]
 },
 "panels": [
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(sloth_slo_info)", "legendFormat": "SLOs" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(sloth_slo_info) by (sloth_service))",
     "legendFormat": "Services"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(slo:current_burn_rate:ratio)",
     "legendFormat": "Avg burn rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{sloth_id!=\"\",sloth_severity=\"ticket\"}) OR on() vector(0)",
     "legendFormat": "Warning alerts"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{sloth_id!=\"\",sloth_severity=\"page\"}) OR on() vector(0)",
     "legendFormat": "Critical alerts"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All burning rate (Filtered >${min_burning_rate}x)",
   "type": "timeseries",
   "description": "The burning rate of the all the Service SLOs",
   "gridPos": { "h": 14, "w": 15, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio > ${min_burning_rate}",
     "legendFormat": "{{sloth_id}}"
    }
   ]
  },
  {
   "title": "Current exceeded burning rate SLOs ",
   "type": "table",
   "description": "The SLOs that currently are burning more error budget that then available",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio > ${min_burning_rate}"
    }
   ]
  },
  {
   "title": "SLOs burn rate state timeline",
   "type": "state-timeline",
   "description": "Shows all the SLOs at the same time burning rate state",
   "gridPos": { "h": 19, "w": 15, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio",
     "legendFormat": "{{sloth_service}}/{{sloth_slo}}"
    }
   ]
  },
  {
   "title": "Budget remaining 30 day window",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 9, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:period_error_budget_remaining:ratio",
     "legendFormat": "{{sloth_id}}"
    }
   ]
  }
 ]
}