{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ase-market.fullname" . }}-postgres
  labels:
    {{- include "ase-market.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgresql.username | quote }}
  password: {{ .Values.postgresql.password | quote }}
  database: {{ .Values.postgresql.database | quote }}
{{- end }}
