{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ase-market.fullname" . }}-postgres
  labels:
    {{- include "ase-market.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "ase-market.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
