- name: Install AWS CLI
  hosts: all
  remote_user: ubuntu
  become: true

  tasks:
    - name: Install AWS CLI
      command: snap install aws-cli --classic
      args:
        creates: /snap/bin/aws

    - name: Test AWS CLI with test credentials
      command: "aws sts get-caller-identity"
      environment:
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        AWS_DEFAULT_REGION: us-east-1
      register: aws_test
      failed_when: false
      changed_when: false

    - name: Show AWS CLI test output
      debug:
        var: aws_test.stdout_lines

    - name: Install Certbot
      command: snap install certbot --classic
      args:
        creates: /snap/bin/certbot

    - name: Allow Certbot plugins to run as root
      command: snap set certbot trust-plugin-with-root=ok
      changed_when: false

    - name: Install Certbot Cloudflare DNS plugin
      command: snap install certbot-dns-cloudflare
      args:
        creates: /snap/bin/certbot-dns-cloudflare