apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflare-token-sync
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloudflare-token-sync
  namespace: cert-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloudflare-token-sync
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloudflare-token-sync
subjects:
  - kind: ServiceAccount
    name: cloudflare-token-sync
    namespace: cert-manager
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-token-sync
  namespace: cert-manager
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: cloudflare-token-sync
          containers:
            - name: cloudflare-token-sync
              image: "aabutouq/cloudflare-token-sync:v1.0.0"
              imagePullPolicy: IfNotPresent
              env:
                - name: AWS_ACCESS_KEY_ID
                  value: "test"
                - name: AWS_SECRET_ACCESS_KEY
                  value: "test"
                - name: LOCALSTACK_ENDPOINT
                  value: "http://192.168.0.158:4566"
                - name: SECRET_ID
                  value: "cloudflare-api-token"
                - name: TARGET_SECRET_NAME
                  value: "cloudflare-api-token"
                - name: TARGET_NAMESPACE
                  value: "cert-manager"
                - name: SECRET_KEY
                  value: "api-token"
              resources:
                requests:
                  cpu: 25m
                  memory: 32Mi
                limits:
                  cpu: 100m
                  memory: 64Mi
